{{- if ((.Values.service.http).port) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    metricsMonitor: {{ .Values.service.http.metricsMonitor.enable | default "true" | quote }} # When overriding must be a string arg, ex: "false" (Within quotes)
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    name: "http"
    port: {{ .Values.service.http.port }}
    targetPort: {{ .Values.service.http.port }}
{{- end -}}
