apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
  {{ if (.Values.service.metrics.publicEndpoint) and eq .Values.service.metrics.publicEndpoint "true" }}
  {{ if (.Values.favorite.drink)                 and eq .Values.favorite.drink "coffee" }}
  - protocol: TCP
    name: "public-endpoint-metrics"
    port: {{ .Values.service.metrics.port }}
    targetPort: {{ .Values.service.metrics.port }}
  {{ end }}
  - protocol: TCP
    name: "ws"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
