apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    {{ if and .Values.service.awsLoadBalancerSSLCert .Values.service.sslPort -}}
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.awsLoadBalancerSSLCert }}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: wss
    {{ end -}}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
  {{ if ((.Values.service.metrics).publicEndpoint) -}} {{ if eq ((.Values.service.metrics).publicEndpoint) "true" }}
  - name: "public-http-endpoint"
    protocol: TCP    
    port: {{ .Values.service.metrics.port }}
    targetPort: {{ .Values.service.metrics.port }}
  {{ end }} {{ end -}}
  - protocol: TCP
    name: "ws"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
 {{ if and .Values.service.awsLoadBalancerSSLCert .Values.service.sslPort .Values.service.targetPort -}}
  - name: "wss"
    protocol: TCP
    port: {{ .Values.service.sslPort }}
    targetPort: {{ .Values.service.targetPort }}
  {{ end -}}