image:
  version: '20230602.1121'
resources:
  limits:
    cpu: 2
    memory: 7Gi
  requests:
    cpu: 0.5
    memory: 4Gi
service:
  additionalResourceTags:
    Environment: prod
annotations:
  prometheus.io/path: metrics
  prometheus.io/port: "3001"
  prometheus.io/scrape: "true"
autoscaling:
  enabled: true
  minReplicas: 51
  maxReplicas: 54
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
rollout:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {}
