namespace: staging-ep-bitswap-peer
image:
  version: '0.15.0'
annotations:
  prometheus.io/path: metrics
  prometheus.io/port: '3001'
  prometheus.io/scrape: 'true'
service:
  additionalResourceTags:
    Environment: staging
env:
  nodeEnv: staging
  peerIdS3Bucket: us-west-2-staging-ep-bitswap-config
  peerAnnounceAddr: /dns4/elastic-staging.dag.house/tcp/443/wss
  dynamodbBlocksTable: staging-ep-blocks
  dynamodbCarsTable: staging-ep-cars
  dynamodbBlocksTableV1: staging-ep-v1-blocks
  dynamodbCarsTableV1: staging-ep-v1-cars
  dynamodbLinkTableV1: staging-ep-v1-blocks-cars-position
  dynamodbConfigTable: staging-ep-bitswap-config
serviceAccountName: staging-ep-bitswap-irsa
