namespace: bitswap-peer
image:
  version: "20220315.1147"
  pullPolicy: Always
service:
  port: 3000
  metrics:
    port: 3001
    publicEndpoint: "true"
    enableMonitor: "false"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 10
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
env:
  nodeEnv: production
  peerIdS3Bucket: ipfs-peer-bitswap-config
  peerIdFileName: peerId.json
  concurrency: 128
  pipelining: 16
  logLevel: info
  cacheBlocksInfo: false
workerType: workerNode
serviceAccountName: bitswap-irsa
