namespace: bitswap-peer
image:
  version: '20220308.1147'
  pullPolicy: Always
service:
  port: 3000
  metricsPort: 3001
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 40
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
env:
  nodeEnv: production
  peerIdS3Bucket: ipfs-peer-bitswap-config
  peerIdFileName: peerId.json
  concurrency: 10000
workerType: workerNode
serviceAccountName: bitswap-irsa
