image:
  version: "20220811.0646"
resources:
  limits:
    cpu: 2
    memory: 3.5Gi
  requests:
    cpu: 2
    memory: 3Gi
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 90
