namespace: bitswap-peer
image:
  version: '20220309.0936'
  pullPolicy: Always
service:
  port: 3000
  metrics:
    port: 3001
    publicEndpoint: "true"
    enableMonitor: "false"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
env:
  nodeEnv: production
  peerIdS3Bucket: ipfs-peer-bitswap-config
  peerIdFileName: peerId.json
  concurrency: 32
  logLevel: info
  cacheBlocksInfo: false
workerType: workerNode
serviceAccountName: bitswap-irsa
