image:
  version: '0.15.0'
resources:
  limits:
    cpu: 4
    memory: 7Gi
  requests:
    cpu: 2
    memory: 6Gi
service:
  additionalResourceTags:
    Environment: prod
annotations:
  prometheus.io/path: metrics
  prometheus.io/port: "3001"
  prometheus.io/scrape: "true"
autoscaling:
  enabled: true
  minReplicas: 30
  maxReplicas: 40
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 90
rollout:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {}
        - setWeight: 60
        - pause: { duration: 10 }
        - setWeight: 80
        - pause: { duration: 10 }
