namespace: dev-ep-bitswap-peer
image:
  version: 20221028.1220-dev
service:
  http:
    metricsMonitor:
      enable: false
    healthCheck:
      enable: false
annotations:
  prometheus.io/path: metrics
  prometheus.io/port: "3001"
  prometheus.io/scrape: "true"
env:
  nodeEnv: dev
  peerIdS3Bucket: us-west-2-dev-ep-bitswap-config
  peerAnnounceAddr: /dns4/elastic-dev.dag.house/tcp/443/wss
  dynamodbBlocksTable: dev-ep-blocks
  dynamodbCarsTable: dev-ep-cars
  dynamodbBlocksTableV1: dev-ep-v1-blocks
  dynamodbCarsTableV1: dev-ep-v1-cars
  dynamodbLinkTableV1: dev-ep-v1-blocks-cars-position
serviceAccountName: dev-ep-bitswap-irsa
autoscaling:
  enabled: false
alpha:
  rollout: 
    strategy:
      canary:
        steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}
