namespace: bitswap-peer
image:
  version: "latest"
  pullPolicy: Always
service:
  deprecatedPort: 3000
  port: 80
  sslPort: 443
  targetPort: 3000
  awsCertificateArn: _argoCDParameterOverride
  http:
    port: 3001
    metricsMonitor:
      enable: "true"
    healthCheck:
      enable: "true"
      liveness: 
        initialDelaySeconds: 15
        periodSeconds: 5
      readiness:
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 10
  additionalResourceTags:
    Team: NearForm
    Project: Elastic IPFS
    Repository: 'https://github.com/elastic-ipfs/bitswap-peer-deployment'
    Stack: 'peer-kubernetes-components'
    ManagedBy: Kubernetes
annotations: {}
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
env:
  nodeEnv: production
  peerIdS3Bucket: ipfs-peer-bitswap-config
  peerIdFileName: peerId.json
  peerAnnounceAddr: /dns4/elastic.dag.house/tcp/443/wss
  awsClientConcurrency: 128
  awsClientPipelining: 8
  logLevel: info
  cacheBlockData: false
  cacheBlockInfo: false
  dynamodbBlocksTable: blocks
  dynamodbCarsTable: cars
  dynamodbBlocksTableV1: prod-ep-v1-blocks
  dynamodbCarsTableV1: prod-ep-v1-cars
  dynamodbLinkTableV1: prod-ep-v1-blocks-cars-position
workerType: workerNode
serviceAccountName: bitswap-irsa
