namespace: dev-ep-bitswap-peer
image:
  version: 20220623.1310-dev
service:
  awsLoadBalancerSSLCert: arnsecret
  sslPort: 3443
  targetPort: 3000
  http:
    metricsMonitor:
      enable: false
    healthCheck:
      enable: false
env:
  nodeEnv: dev
  peerIdS3Bucket: us-west-2-dev-ep-bitswap-config
  dynamodbBlocksTable: dev-ep-blocks
  dynamodbCarsTable: dev-ep-cars
serviceAccountName: dev-ep-bitswap-irsa
