namespace: staging-ep-bitswap-peer
image:
  version: "20220525.2105"
service:
  metrics:
    enableMonitor: "false"
env:
  nodeEnv: staging
  peerIdS3Bucket: us-west-2-staging-ep-bitswap-config
  dynamodbBlocksTable: staging-ep-blocks
  dynamodbCarsTable: staging-ep-cars
serviceAccountName: staging-ep-bitswap-irsa
