namespace: staging-ep-bitswap-peer
image:
  version: "20221017.1404"
annotations:
  prometheus.io/path: metrics
  prometheus.io/port: "3001"
  prometheus.io/scrape: "true"
env:
  nodeEnv: staging
  peerIdS3Bucket: us-west-2-staging-ep-bitswap-config
  peerAnnounceAddr: /dns4/elastic-staging.dag.house/tcp/443/wss
  dynamodbBlocksTable: staging-ep-blocks
  dynamodbCarsTable: staging-ep-cars
  dynamodbBlocksTableV1: staging-ep-v1-blocks
  dynamodbCarsTableV1: staging-ep-v1-cars
  dynamodbLinkTableV1: staging-ep-v1-blocks-cars-position
serviceAccountName: staging-ep-bitswap-irsa
alpha:
  rollout:
    strategy:
      canary:
        steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}
