image:
  version: "20220707.1226"
resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 2
    memory: 3Gi
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 300
  targetCPUUtilizationPercentage: 50
