namespace: bitswap-peer
image:
  version: "20220406.1828"
  pullPolicy: Always
service:
  port: 3000
  metrics:
    port: 3001
    publicEndpoint: "true"
    enableMonitor: "true"
resources:
  limits:
    cpu: 4
    memory: 2.6Gi
  requests:
    cpu: 3
    memory: 2Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 40
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
env:
  nodeEnv: production
  peerIdS3Bucket: ipfs-peer-bitswap-config
  peerIdFileName: peerId.json
  concurrency: 128
  pipelining: 16
  logLevel: info
  cacheBlocksInfo: false
workerType: workerNode
serviceAccountName: bitswap-irsa
