namespace: staging-ep-bitswap-peer
image:
  version: "20220629.1405"
env:
  nodeEnv: staging
  peerIdS3Bucket: us-west-2-staging-ep-bitswap-config
  dynamodbBlocksTable: staging-ep-blocks
  dynamodbCarsTable: staging-ep-cars
serviceAccountName: staging-ep-bitswap-irsa
