image:
  version: "20220812.0910"
resources:
  limits:
    cpu: 2
    memory: 3.5Gi
  requests:
    cpu: 2
    memory: 3Gi
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 90