image:
  version: "20220624.1201"
service:
  metrics:
    port: 3001
    enableMonitor: "true"
resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 3
    memory: 4Gi
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 300
