image:
  version: "20221017.1404"
resources:
  limits:
    cpu: 4
    memory: 7Gi
  requests:
    cpu: 4
    memory: 6Gi
autoscaling:
  enabled: true
  minReplicas: 10
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 90
