image:
  version: '20230706.1346'
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 3Gi
service:
  additionalResourceTags:
    Environment: prod
annotations:
  prometheus.io/path: metrics
  prometheus.io/port: "3001"
  prometheus.io/scrape: "true"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 72
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 40
rollout:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {}
