image:
  version: "20220707.1226"
resources:
  limits:
    cpu: 2
    memory: 3.5Gi
  requests:
    cpu: 2
    memory: 3Gi
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
