namespace: dev-ep-bitswap-peer
image:
  version: 20220914.0530-dev
service:
  http:
    metricsMonitor:
      enable: false
    healthCheck:
      enable: false
env:
  nodeEnv: dev
  peerIdS3Bucket: us-west-2-dev-ep-bitswap-config
  peerAnnounceAddr: /dns4/elastic-dev.dag.house/tcp/443/wss
  dynamodbBlocksTable: dev-ep-blocks
  dynamodbCarsTable: dev-ep-cars
  dynamodbBlocksTableV1: dev-ep-v1-blocks
  dynamodbCarsTableV1: dev-ep-v1-cars
  dynamodbLinkTableV1: dev-ep-v1-blocks-cars-position
serviceAccountName: dev-ep-bitswap-irsa
