namespace: bitswap-peer
image:
  version: 'latest'
  pullPolicy: Always
service:
  deprecatedPort: 3000
  port: 80
  sslPort: 443
  targetPort: 3000
  awsCertificateArn: _argoCDParameterOverride
  http:
    port: 3001
    metricsMonitor:
      enable: 'true'
    healthCheck:
      enable: 'true'
      liveness:
        initialDelaySeconds: 15
        periodSeconds: 5
      readiness:
        initialDelaySeconds: 15
        periodSeconds: 5
annotations: {}
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
env:
  - name: NODE_ENV
    value: production
workerType: workerNode
serviceAccountName: bitswap-irsa
