namespace: dev-ep-bitswap-peer
image:
  version: 20220623.1310-dev
service:
  http:
    metricsMonitor:
      enable: false
    healthCheck:
      enable: false
env:
  nodeEnv: dev
  peerIdS3Bucket: us-west-2-dev-ep-bitswap-config
  peerAnnounceAddr: /dns4/dev.peer.ipfs-elastic-provider-aws.com/tcp/3000/ws
  dynamodbBlocksTable: dev-ep-blocks
  dynamodbCarsTable: dev-ep-cars
serviceAccountName: dev-ep-bitswap-irsa
