image:
  version: '20230602.1121'
resources:
  limits:
    cpu: 3
    memory: 7Gi
  requests:
    cpu: 2
    memory: 4Gi
service:
  additionalResourceTags:
    Environment: prod
annotations:
  prometheus.io/path: metrics
  prometheus.io/port: "3001"
  prometheus.io/scrape: "true"
autoscaling:
  enabled: true
  minReplicas: 20
  maxReplicas: 60
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 90
rollout:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {}
        - setWeight: 60
        - pause: { duration: 10 }
        - setWeight: 80
        - pause: { duration: 10 }
