namespace: bitswap-peer
image:
  version: "20220513.1754"
resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 3
    memory: 2Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 40
