namespace: dev-ep-bitswap-peer
image:
  version: 20220607.2155-dev
service:
  metrics:
    enableMonitor: "false"
env:
  nodeEnv: dev
  peerIdS3Bucket: us-west-2-dev-ep-bitswap-config
  dynamodbBlocksTable: dev-ep-blocks
  dynamodbCarsTable: dev-ep-cars
serviceAccountName: dev-ep-bitswap-irsa
