namespace: dev-ep-bitswap-peer
image:
  version: 20220601.1858-dev
service:
  http:
    port: 3001
    enableMetricsMonitor: "false"
    enableHealthCheck: "true"
env:
  nodeEnv: dev
  peerIdS3Bucket: us-west-2-dev-ep-bitswap-config
  dynamodbBlocksTable: dev-ep-blocks
  dynamodbCarsTable: dev-ep-cars
serviceAccountName: dev-ep-bitswap-irsa
