namespace: dev-ep-bitswap-peer
image:
  version: 20220704.1416-dev
service:
  http:
    metricsMonitor:
      enable: false
    healthCheck:
      enable: false
env:
  nodeEnv: dev
  peerIdS3Bucket: us-west-2-dev-ep-bitswap-config
  dynamodbBlocksTable: dev-ep-blocks
  dynamodbCarsTable: dev-ep-cars
  dynamodbBlocksTableV1: dev-v1-blocks
  dynamodbCarsTableV1: dev-v1-cars
  dynamodbLinkTableV1: dev-v1-blocks-cars
serviceAccountName: dev-ep-bitswap-irsa
